// Code generated by goctl. DO NOT EDIT!
// Source: sendmessage.proto

package server

import (
	"context"

	"github.com/1005281342/go-task/sendmessage/internal/logic"
	"github.com/1005281342/go-task/sendmessage/internal/svc"
	"github.com/1005281342/go-task/sendmessage/sendmessage"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	sendmessage.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServer) Send(ctx context.Context, in *sendmessage.SendReq) (*sendmessage.SendRsp, error) {
	l := logic.NewSendLogic(ctx, s.svcCtx)
	return l.Send(in)
}
