// Code generated by goctl. DO NOT EDIT!
// Source: manager.proto

package server

import (
	"context"

	"github.com/1005281342/go-task/manager/internal/logic"
	"github.com/1005281342/go-task/manager/internal/svc"
	"github.com/1005281342/go-task/manager/manager"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	manager.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServer) Add(ctx context.Context, in *manager.AddReq) (*manager.AddRsp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
